### ISSUE TITLE
Sugguestion

### ISSUE THREAD

**Issue by DaPigGuy** [alejandroliu/bad-plugins#1]
I have a sugguestion. Can you add changing passwords for SimpleAuthHelper?

**Comment by DaPigGuy** [comment]
Also, can you add how many times you can try logging in before getting kicked. So if its set to 5, i'll get kicked if I use an incorrect password 5 times.

**Comment by TonyDroidd** [comment]
Good idea :D

**Comment by alejandroliu** [comment]
ON changing passwords, what exactly do you mean?  Like a password expiration?   or a command to change passwords?

**Comment by alejandroliu** [comment]
I was looking at the SimpleAuth code, unfortunately there is no API to change the password.  SimpleAuthHelper is a SimpleAuth **helper** not a replacement.

This could be implemented with the `/unregister` command which is listed as a **TODO** in the SimpleAuth documentation.

I think you should suggest to the PM team to add the change password functionality properly or the `/unregister` command.

**Comment by alejandroliu** [comment]
Done...
