### ISSUE TITLE
Mobsters: ERROR

### ISSUE THREAD

**Issue by kvetinac97** [alejandroliu/bad-plugins#10]
When I run Mobsters, it writes me:

ERROR in Block:: $creative....

in Main.php ~ please fix

**Comment by Guillaume351** [comment]
I was going to ask him to fix too :) Not sure he can, a lot of things changed I guess

**Comment by alejandroliu** [comment]
I was hoping that v1.5 would have brought mobs so I wasn't doing much with Mobsters.

**Comment by kvetinac97** [comment]
OK :( it's sad

**Comment by kvetinac97** [comment]
I hoped this plugin can be updated for v0.11.1...

**Comment by alejandroliu** [comment]
OK, 0.4.0 should work with 0.11.0.

**Comment by Guillaume351** [comment]
THANKS ! However, friendly animals have their head moving fast in all direction and never moves, squeletons don't move either

**Comment by alejandroliu** [comment]
Well, it is incomplete. I only updated so it works with 1.5. 

The only ones that have any sort of meaningful code are zombies and wolves. 

You are free to fork and implement the rest.
