### ISSUE TITLE
Spawning?

### ISSUE THREAD

**Issue by spideyroc1** [alejandroliu/bad-plugins#11]
Is there anyway to make the mobs spawn without a spawn egg. Not a command but naturally like single player. I dont necessarily care about if its day or night. Is there a addon for this or any way to. If i were to make a plugin what function would i use to spawn the mob

**Comment by alejandroliu** [comment]
You need to write a custom plugin for that.  There is no easy API function to do this.
All entities (mobs and items) are spawned the same way.  So if you find code to spawn any entity, the same would apply to a mob.  You would need to populate the namedtag structure.
