### ISSUE TITLE
spawners...

### ISSUE THREAD

**Issue by MrDoni98** [alejandroliu/bad-plugins#13]
Please add spawner mobs, some call for an egg to touch him, he was such a mob will spawn.
(my English is bad)

**Comment by alejandroliu** [comment]
No idea what you mean here.

**Comment by MrDoni98** [comment]
spawner block (id 52) will spawn mobs,eggs which have touched on it(google translator)

**Comment by alejandroliu** [comment]
Oh no... not planning on doing that.  You can use signs to achieve a similar result.
