### ISSUE TITLE
help for LocalChat

### ISSUE THREAD

**Issue by MrDoni98** [alejandroliu/bad-plugins#15]
how to change the color of the message?

public function onChat(PlayerChatEvent $e){
        if ($e->isCancelled()) return;
        $pw = $e->getPlayer();
        // Non players are handled normally
        if (!($pw instanceof Player)) return;
                $msg = $e->getMessage();
        if (substr($msg,0,1) == ":") {
            // This messages goes to everybody on the server...
            // no need to do much...
            if (!$this->access($pw,"localchat.broadcast.server")) {
                $e->setCancelled();
                return;
            }
            $e->setMessage(substr($msg,1));
            return;
        }

**Comment by alejandroliu** [comment]
For the normal chat message you need to do $e->setFormat.

On the other hand, it should be compatible with other chat plugins that define chat formats.

**Comment by MrDoni98** [comment]
thank you very much
