### ISSUE TITLE
LIAB: DataFolder is never created..

### ISSUE THREAD

**Issue by inxomnyaa** [alejandroliu/bad-plugins#18]
I do not understand why, but there will be no folder generated, so the whole thing doesn't save the inventorys.. No errors in console EDIT: only for OP'd players.

Also, with alwaysspawn.. well when the player respawns he has the last inventory.
So he looses the items. (For example when the server stops, the player rejoins..)

Could you add that some worlds can share the same inventory? i have a world where you can farm items and i would like the players to have the items on another world (the building world)

**Comment by alejandroliu** [comment]
Do you get any error messages when the server starts?  The folder is created in line 21, so if it isn't you should get an error.

**Comment by inxomnyaa** [comment]
No, thats why i wonder, if i join as non opped player this works

**Comment by alejandroliu** [comment]
Ah... that's a feature.  Players with "liab.keep" permission are excempt of LIAB.

**Comment by inxomnyaa** [comment]
Oh. :D well my OP's can't play normal because of all the plugins..
most of them use op permissions as default. we now have seperate accounts.
Thanks for the help :) :+1:
