### ISSUE TITLE
Another suggestion

### ISSUE THREAD

**Issue by DaPigGuy** [alejandroliu/bad-plugins#2]
Can you add a feature where when someone register, commands (configured in config.yml) will run. The same for login, but registering and logging in can have different commands. Example: If I put "say @Player is a new player!" for register, it will run that command when someone registers. If i put "tell @Player Welcome back, @Player!" For login, it will run that command when someone logins.

**Comment by DaPigGuy** [comment]
Kinda like the nest-eggs

**Comment by DaPigGuy** [comment]
Oh BTW, thx for adding changing passwords and resetting someone's password.

**Comment by alejandroliu** [comment]
Yes, I submitted a PullRequest to SimpleAuth to implement the unregister command.  But figure I could also implement the same thing in Helper.

If they accept my PR and after a new version of SimpleAuth is published I will remove the resetpwd command.  I will probably keep the chpwd as it is a little bit safer than doing unregister.

The running commands when people register/log-in will not implement yet, as it feels beyond the capabilities of the Helper.  (It is not an easy problem to solve in general).

**Comment by DaPigGuy** [comment]
Can you add VeinMiner to ToyBox?

**Comment by alejandroliu** [comment]
Added a VeinMiner to ToyBox.  (I think it is right).

If you can please test it at [ToyBox-1.2.1dev1](https://github.com/alejandroliu/pocketmine-plugins/releases/tag/ToyBox-1.2.1dev1)
