### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DaPigGuy** [alejandroliu/bad-plugins#3]
When i'm using the newest version of SimpleAuthHelper, I keep getting errors. When i check the lines causing them, all of the lines have:   echo **METHOD**.",".**LINE**."($n)\n"; //##DEBUG;

**Comment by DaPigGuy** [comment]
After i removed all the     echo **METHOD**.",".**LINE**."($n)\n"; //##DEBUG; ,I don't get the errors no more.

**Comment by alejandroliu** [comment]
You are using the source version or the phar version?

**Comment by DaPigGuy** [comment]
Source

**Comment by DaPigGuy** [comment]
Everything works fine after i removed all the   echo **METHOD**.",".**LINE**."($n)\n"; //##DEBUG; , no errors or crashes. I think they are causing it.

**Comment by alejandroliu** [comment]
Those are trace lines that I use when testing/debugging.  They are harmless.  My mkplugin.php script will strip those when creating a phar file.

**Comment by DaPigGuy** [comment]
Ok.

**Comment by alejandroliu** [comment]
If you are using the source, just delete them (or use the phar file)

**Comment by DaPigGuy** [comment]
I already did ;)
