### ISSUE TITLE
Suggestion: Customize Mob Drops

### ISSUE THREAD

**Issue by DaPigGuy** [alejandroliu/bad-plugins#7]
Can you add a feature to Mobsters where you can customize a mob's drops in a config?

Config Example:

zombie:
- FEATHER
  creeper: 
- GUNPOWDER
  etc.

**Comment by alejandroliu** [comment]
Is this still needed?

**Comment by alejandroliu** [comment]
Will not implement this as part of mobsters.  Mobsters is about providing moving mobs.

Plugins can change the Drops by hooking EntityDeathEvent.
