### ISSUE TITLE
pmptemplate help

### ISSUE THREAD

**Issue by MrDoni98** [alejandroliu/bad-plugins#8]
how create more model?

**Comment by alejandroliu** [comment]
Did it work for you?  I am surprised.

The models are the clipboard save from my WorldEditor plugin:

https://github.com/alejandroliu/plugin-remakes/tree/master/WorldEditor

**Comment by MrDoni98** [comment]
ahah, I have not tested it, just I saw your video onpocketmine.net

**Comment by MrDoni98** [comment]
I was hooked, and the idea for the mini-games

**Comment by alejandroliu** [comment]
That video was only a test (to see what could be done).  It worked on 1.4 (with lots of glitches).  I will probably think of something else for 1.5.

**Comment by MrDoni98** [comment]
Sad (( and you will fix it?

**Comment by MrDoni98** [comment]
Its Great idea!
